jobs/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name= "jobs"
urlpatterns = [
    
    path('', HomeView.as_view(), name='home'),
    path('/create-job/', CreateJobView.as_view(), name='create-job'),
    path('search/', SearchJobView.as_view(), name='search'),
    path('detail/<slug>/<int:pk>/', SingleJobView.as_view(), name='single-job'),
    path('update/<slug>/<int:pk>/', UpdateJobView.as_view(), name='update-job'),
    path('delete/<slug>/<int:pk>/', DeleteJobView.as_view(), name='delete-job'),
    path('category-detail/<slug>/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),

]

users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as authViews
from django.urls import reverse_lazy
app_name= "users"


urlpatterns =[

	path('register', UserRegisterView.as_view(), name="register"),
	path('login/', UserLoginView.as_view(), name="login"),
	path('logout/', UserLogoutView.as_view(), name="logout"),
	path('password-change/', authViews.PasswordChangeView.as_view(success_url = reverse_lazy('users:password_change_done')), name="password_change"),
	path('password-change-done/', authViews.PasswordChangeDoneView.as_view(), name="password_change_done"),
	
	path('update-profile/<int:pk>/', UserUpdateView.as_view(), name="update_profile"),
	path('employee-profile/<int:employee_id>/<int:job_id>/', EmployeeProfileView.as_view(), name="employee_profile"),
	path('employer-jobs/', EmployerPostedJobsView.as_view(), name="employer_jobs"),
	path('employee-messages/<int:pk>/', EmployeeMessagesView.as_view(), name="employer_messages"),
	path('employee-display-messages/<int:pk>/', EmployeeDisplayMessages.as_view(), name="employee_display_messages"),
	path('add-wishlist/<int:pk>/', AddWishListView.as_view(), name="add-wishlist"),
	path('remove-from-wishlist/<int:pk>/', RemoveFromWishListView.as_view(), name="remove_from_wishlist"),
	path('mywishlist/<int:pk>/', MyWishList.as_view(), name="my_wish_list"),



]

jobs/models.py
from django.db import models
from jobPortal import settings
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField
# Create your models here.
class Category(models.Model):
	title= models.CharField(max_length=100)
	slug= models.SlugField(default=None, editable=False)


	def __str__(self):
		return self.title


	def save(self, *args, **kwargs):
		self.slug= slugify(self.title)
		super(Category, self).save(*args, **kwargs)


	def job_count(self):
		return self.jobs.all().count()









class Job(models.Model):
	title= models.CharField(max_length=300)
	company=models.CharField(max_length=300)
	CHOICES=(

			('full_time','Full Time'),
			('part_time','Part Time'),
			('freelance','Freelance'),
			('internship','Internship'),
			('temporary','Temporary'),
			)


	job_type=models.CharField(max_length=20,blank=False,default=None,choices=CHOICES)
	location= models.CharField(max_length=200,blank=False, default=None)
	description=RichTextField(blank=False, default=None)
	publishing_date=models.DateTimeField(auto_now_add=True)
	slug=models.SlugField(default=None, editable=False)
	employer=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default= None)
	employee= models.ManyToManyField(settings.AUTH_USER_MODEL,default=None, blank=True, related_name="job_employee")
	category =models.ForeignKey(Category, on_delete=models.CASCADE, related_name="jobs")
	

	def __str__(self):
		return self.title


	def save(self, *args, **kwargs):
		self.slug=slugify(self.title)
		super(Job, self).save(*args, **kwargs)


	class Meta:
		ordering=('-id',)

jobs/forms.py
from django import forms

from .models import *



class CreateJobForm(forms.ModelForm):
	class Meta:
		model= Job 
		fields=['title', 'company', 'location', 'job_type', 'category', 'description']
		widgets={'job_type':forms.RadioSelect}




class ApplyJobForm(forms.ModelForm):
	class Meta:
		model= Job
		fields= []



class UpdateJobForm(forms.ModelForm):
	class Meta:
		model= Job 
		fields=['title', 'company', 'location', 'job_type', 'category', 'description']
		widgets={'job_type':forms.RadioSelect}

		

jobs/views.py
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
# Create your views here.
from .models import Job, Category
from users.models import Account, Profile
from django.contrib.messages.views import SuccessMessageMixin
from .forms import *
from django.views.generic import DetailView
from django.shortcuts import get_object_or_404
from django.db.models.query_utils import Q
from django.urls import reverse
from django.http import HttpResponseRedirect

class HomeView(ListView):
	template_name='jobs/index.html'
	context_object_name='jobs'
	model=Job
	paginate_by=2

	# for additional context
	def get_context_data(self, **kwargs):
		context= super(HomeView,self).get_context_data(**kwargs)
		context['categories']=Category.objects.all()
		context['all_jobs']=Job.objects.all().count()*1997
		context['candidates']=Account.objects.filter(is_employee=True).count()* 1555
		context['resumes']=Profile.objects.exclude(resume="").count()*1476
		context['employers']=Account.objects.filter(is_employer=True).count()* 1255
		if self.request.user.is_authenticated:
			context['wish_list']=Job.objects.filter(wish_list__user_id=self.request.user.id).values_list('id', flat=True)

		return context



@method_decorator(login_required(login_url='/users/login'), name='dispatch')
class CreateJobView(SuccessMessageMixin, CreateView ):
	model= Job
	template_name= 'jobs/create-jobs.html'
	form_class=CreateJobForm
	success_url = '/job'
	success_message="Job has been posted"

	def form_valid(self, form):
		job= form.save(commit=False)
		job.employer=self.request.user
		job.save()
		return super(CreateJobView,self).form_valid(form)


class SingleJobView(SuccessMessageMixin, UpdateView):
	template_name='jobs/single.html'
	model=Job
	context_object_name="job"
	form_class= ApplyJobForm
	success_message= "You Applied this job!"

	def get_context_data(self, **kwargs):
		context= super(SingleJobView,self).get_context_data(**kwargs)
		context['categories']=Category.objects.all()
		context['employee_applied']=Job.objects.get(pk=self.kwargs['pk']).employee.all().filter(id=self.request.user.id)
		context['in_my_list']=Job.objects.get(pk=self.kwargs['pk']).wish_list.all().filter(user_id=self.request.user.id)
		try:	
			context['applied_employees']=  Job.objects.get(pk=self.kwargs['pk'],employer_id=self.request.user.id).employee.all()
			context['employer_id']= Job.objects.get(pk=self.kwargs['pk']).employer_id
		except:
			pass
		return context

	def form_valid(self, form):
		employee=self.request.user
		form.instance.employee.add(employee)
		form.save()
		return super(SingleJobView, self).form_valid(form)

	def get_success_url(self):
		return reverse('jobs:single-job', kwargs={'slug':self.object.slug, "pk":self.object.pk})

class CategoryDetailView(ListView):
	model=Job
	template_name='jobs/category-detail.html'
	context_object_name= 'jobs'
	paginate_by=2

	def get_queryset(self):
		self.category =get_object_or_404(Category,pk=self.kwargs['pk'])
		return Job.objects.filter(category=self.category)

	def get_context_data(self, *args,**kwargs):
		context=super(CategoryDetailView,self).get_context_data(*args,**kwargs)
		self.category =get_object_or_404(Category,pk=self.kwargs['pk'])
		context['categories']=Category.objects.all()
		context['category']=self.category

		return context


class SearchJobView(ListView):
	model=Job
	template_name= 'jobs/search.html'
	paginate_by=2
	context_object_name='jobs'


	def get_queryset(self):
		q1=self.request.GET.get("job_title")
		q2=self.request.GET.get("job_type")
		q3=self.request.GET.get("job_location")


		if q1 or q2 or q3:
			return Job.objects.filter(
									 Q(title__icontains=q1)|
									 Q(description__icontains=q1),

									 job_type=q2, 
									 location__icontains=q3
									 ).order_by('-id')

		return Job.objects.all().order_by('-id')

	def get_context_data(self, *args,**kwargs):
		context=super(SearchJobView,self).get_context_data(*args,**kwargs)
		context['categories']=Category.objects.all()
		
		return context


class UpdateJobView(SuccessMessageMixin, UpdateView):
	model= Job
	template_name= 'jobs/update.html'
	form_class=UpdateJobForm
	success_message= "You Updated Your Job!"

	def form_valid(self, form):
		form.instance.employer=self.request.user
		return super(UpdateJobView, self).form_valid(form)


	def get(self, request, *args, **kwargs):
		self.object= self.get_object()
		if self.object.employer != request.user:
			return HttpResponseRedirect('/job')

		return super(UpdateJobView, self).get(request, *args, **kwargs)

	def get_success_url(self):
		return reverse('jobs:single-job', kwargs={"pk":self.object.pk, "slug":self.object.slug})



class DeleteJobView(SuccessMessageMixin, DeleteView):
	model= Job
	success_url= '/job'
	template_name= 'jobs/delete.html'


	def delete(self, request, *args, **kwargs):
		self.object= self.get_object()
		if self.object.employer== request.user:
			self.object.delete()
			return HttpResponseRedirect(self.success_url)
		else:
			return HttpResponseRedirect(self.success_url)



	def get(self, request, *args, **kwargs):
		self.object= self.get_object()
		if self.object.employer != request.user:
			return HttpResponseRedirect('/job')

		return super(DeleteJobView, self).get(request, *args, **kwargs)

templates/jobs/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>JobPortal - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700,800,900" rel="stylesheet">

  <link rel="stylesheet" href="{% static "css/open-iconic-bootstrap.min.css" %} ">
    <link rel="stylesheet" href="{% static "css/animate.css" %} ">
    
    <link rel="stylesheet" href="{% static "css/owl.carousel.min.css" %} ">
    <link rel="stylesheet" href="{% static "css/owl.theme.default.min.css" %} ">
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %} ">

    <link rel="stylesheet" href="{% static "css/aos.css" %} ">

    <link rel="stylesheet" href="{% static "css/ionicons.min.css" %} ">

    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.css" %} ">
    <link rel="stylesheet" href="{% static "css/jquery.timepicker.css" %} ">

    
    <link rel="stylesheet" href="{% static "css/flaticon.css" %} ">
    <link rel="stylesheet" href="{% static "css/icomoon.css" %} ">
    <link rel="stylesheet" href="{% static "css/style.css" %} ">
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>


  </head>
  <body>	 






<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
 <div class="container">
  <a class="navbar-brand" href="index.html">JobPortal</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="oi oi-menu"></span> Menu
  </button>

  <div class="collapse navbar-collapse" id="ftco-nav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active"><a href="{% url 'jobs:home' %}" class="nav-link">Home</a></li>
      <li class="nav-item"><a href="about.html" class="nav-link">About</a></li>
      <li class="nav-item"><a href="blog.html" class="nav-link">Blog</a></li>
      <li class="nav-item"><a href="contact.html" class="nav-link">Contact</a></li>

      {% if not user.is_authenticated %}
      <li class="nav-item cta mr-md-2"><a href="{% url 'users:register' %}" class="nav-link">Register</a></li>
      <li class="nav-item cta cta-colored"><a href="{% url 'users:login' %}" class="nav-link">Login</a></li>
      {% endif %}

      {% if user.is_authenticated and user.is_employee %}
      <!-- Example single danger button -->
			<div class="btn-group">
			  <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height:50px">
			     {{ user.first_name }}
			  </button>
			  <div class="dropdown-menu">
			    <a class="dropdown-item" href="#">My Jobs</a>
			    <a class="dropdown-item" href="{% url 'users:employer_messages' pk=user.pk %}">You Have {{ user.count_unread_messages }} message(s)</a>
			    <a class="dropdown-item" href="{% url 'users:update_profile' pk=user.get_profile_id %}">Update Profile</a>

           <a class="dropdown-item" href="{% url 'users:password_change' %}">Change Password</a>

          <a class="dropdown-item" href="{% url 'users:my_wish_list' pk=user.id %}">My Wish List</a>

			    <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
			  </div>
			</div>

      {% endif %}

       {% if user.is_authenticated and user.is_employer %}
      <!-- Example single danger button -->
			<div class="btn-group">
			  <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height:50px">
			    {{ user.first_name }}
			  </button>
			  <div class="dropdown-menu">
			    <a class="dropdown-item" href="{% url 'jobs:create-job' %}">Add Job</a>
			    <a class="dropdown-item" href="{% url 'users:employer_jobs' %}">My Jobs</a>
			    {% if user.get_profile_id %}
			    <a class="dropdown-item" href="{% url 'users:update_profile' pk=user.get_profile_id %}"> Update Profile</a>
			    {% endif %}

           <a class="dropdown-item" href="{% url 'users:password_change' %}">change Password</a>
			    <div class="dropdown-divider"></div>
			    <a class="dropdown-item" href="{% url 'users:logout' %}">Logout</a>
			  </div>
			</div>

      {% endif %}


    </ul>
  </div>
</div>
</nav>


	  <!-- end Nav -->

	  {% block content %}


	  {% endblock %}

		
		<section class="ftco-section-parallax">
      <div class="parallax-img d-flex align-items-center">
        <div class="container">
          <div class="row d-flex justify-content-center">
            <div class="col-md-7 text-center heading-section heading-section-white ftco-animate">
              <h2>Subcribe to our Newsletter</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in</p>
              <div class="row d-flex justify-content-center mt-4 mb-4">
                <div class="col-md-8">
                  <form action="#" class="subscribe-form">
                    <div class="form-group d-flex">
                      <input type="text" class="form-control" placeholder="Enter email address">
                      <input type="submit" value="Subscribe" class="submit px-3">
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>



    <footer class="ftco-footer ftco-bg-dark ftco-section">
      <div class="container">
        <div class="row mb-5">
        	<div class="col-md">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">About</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-3">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Employers</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">How it works</a></li>
                <li><a href="#" class="py-2 d-block">Register</a></li>
                <li><a href="#" class="py-2 d-block">Post a Job</a></li>
                <li><a href="#" class="py-2 d-block">Advance Skill Search</a></li>
                <li><a href="#" class="py-2 d-block">Recruiting Service</a></li>
                <li><a href="#" class="py-2 d-block">Blog</a></li>
                <li><a href="#" class="py-2 d-block">Faq</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-4">
              <h2 class="ftco-heading-2">Workers</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">How it works</a></li>
                <li><a href="#" class="py-2 d-block">Register</a></li>
                <li><a href="#" class="py-2 d-block">Post Your Skills</a></li>
                <li><a href="#" class="py-2 d-block">Job Search</a></li>
                <li><a href="#" class="py-2 d-block">Emploer Search</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
          </div>
        </div>
      </div>
    </footer>


  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'js/jquery.timepicker.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'js/google-map.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

  {% if user.is_authenticated and user.is_employee %}
  <script src="{% static 'js/addorremove.js' %}"></script>

  {% else %}
 <script src="{% static 'js/addorremove2.js' %}"></script>


 {% endif %}




    
  </body>
</html>

templates/jobs/single.html
{% extends 'jobs/base.html' %}

{% load static %}

{% block content %}

    
     <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-3"><a href="blog.html">Blog <i class="ion-ios-arrow-forward"></i></a></span> <span>Single</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Job Detail</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-md-8 ftco-animate">
            <h2 class="mb-3">{{ job.title }}</h2>
            <p>{{ job.description|safe }}</p>
            <hr>
            <form method="post">
              {% csrf_token %}
            {% if user.is_employee %}

            
            <div class="ml-auto d-flex">
              {% if employee_applied %}
               <input type="submit" value="Apply" class="btn btn-primary py-2 mr-1" disabled  title="You Already applied">
              {% else %}
             
              <input type="submit" value="Apply" class="btn btn-primary py-2 mr-1">


               {% if in_my_list %}

                <a href="javascripts:void(0);" onclick="addorremove({{job.id}})" id="jobwl{{job.id}}" title="Remove from my wish list" class="btn btn-danger rounded-circle btn-favorite d-flex align-items-center">
                  <span class="icon-heart"></span>
                </a>
                {% else %}

                 <a href="javascripts:void(0);" onclick="addorremove({{job.id}})" id="jobwl{{job.id}}" title="Add to wish list" class="btn btn-primary rounded-circle btn-favorite d-flex align-items-center">
                  <span class="icon-heart"></span>
                </a>
                {%endif%}

           
                {% endif %}
              </div>

            {% endif %}
          </form>

          {% if user.is_employer and user.id == employer_id %}
            {% if applied_employees  %}
          
        <div class="list-group">
          <button type="button" class="list-group-item list-group-item-action active" style="text-align:center">
            Applied Candidates
          </button>


          {% for employee in applied_employees %}
          <a href="{% url 'users:employee_profile' employee_id=employee.pk job_id=job.id %}" class="list-group-item list-group-item-action">{{ employee.first_name }}  {{employee.last_name}}</a>
           {% endfor %}
        </div>
        {% else %}
          <div class="list-group">
          <button type="button" class="list-group-item list-group-item-action active" style="text-align:center">
            No Applied Candidates
          </button>


       
      </div>

{% endif %}

  <div class="tag-widget post-tag-container mb-5 mt-5">
        
        <a href="{% url 'jobs:delete-job' slug=job.slug pk=job.pk%}" class="btn btn-danger py-2 mr-1">Delete</a>
        <a href="{% url 'jobs:update-job' slug=job.slug pk=job.pk%}" class="btn btn-primary py-2 mr-1">Update</a>
      </div>
{% endif %}
            <p>
              <img src="images/image_7.jpg" alt="" class="img-fluid">
            </p>
            






            <div class="tag-widget post-tag-container mb-5 mt-5">
              <div class="tagcloud">
                <a href="#" class="tag-cloud-link">Life</a>
                <a href="#" class="tag-cloud-link">Sport</a>
                <a href="#" class="tag-cloud-link">Tech</a>
                <a href="#" class="tag-cloud-link">Travel</a>
              </div>
            </div>
            




          </div> <!-- .col-md-8 -->
          <div class="col-md-4 sidebar ftco-animate">
            <div class="sidebar-box">
              <form action="#" class="search-form">
                <div class="form-group">
                  <span class="icon icon-search"></span>
                  <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                </div>
              </form>
            </div>
            <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3>Categories</h3>
                {% for category in categories %}
                <li><a href="#">{{ category.title }}<span>{{ category.job_count }}</span></a></li>
               {% endfor %}
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Recent Blog</h3>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_1.jpg);"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_2.jpg);"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_3.jpg);"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Tag Cloud</h3>
              <div class="tagcloud">
                <a href="#" class="tag-cloud-link">dish</a>
                <a href="#" class="tag-cloud-link">menu</a>
                <a href="#" class="tag-cloud-link">food</a>
                <a href="#" class="tag-cloud-link">sweet</a>
                <a href="#" class="tag-cloud-link">tasty</a>
                <a href="#" class="tag-cloud-link">delicious</a>
                <a href="#" class="tag-cloud-link">desserts</a>
                <a href="#" class="tag-cloud-link">drinks</a>
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Paragraph</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
            </div>
          </div>

        </div>
      </div>
    </section> <!-- .section -->


    <script type="text/javascript">





    </script>

























		{% endblock %}
    