jobs/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

app_name= "jobs"
urlpatterns = [
    
    path('', HomeView.as_view(), name='home'),
    path('/create-job/', CreateJobView.as_view(), name='create-job'),
    path('search/', SearchJobView.as_view(), name='search'),
    path('detail/<slug>/<int:pk>/', SingleJobView.as_view(), name='single-job'),
    path('update/<slug>/<int:pk>/', UpdateJobView.as_view(), name='update-job'),
    path('delete/<slug>/<int:pk>/', DeleteJobView.as_view(), name='delete-job'),
    path('category-detail/<slug>/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),

]

users/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as authViews
from django.urls import reverse_lazy
app_name= "users"


urlpatterns =[

	path('register', UserRegisterView.as_view(), name="register"),
	path('login/', UserLoginView.as_view(), name="login"),
	path('logout/', UserLogoutView.as_view(), name="logout"),
	path('password-change/', authViews.PasswordChangeView.as_view(success_url = reverse_lazy('users:password_change_done')), name="password_change"),
	path('password-change-done/', authViews.PasswordChangeDoneView.as_view(), name="password_change_done"),
	
	path('update-profile/<int:pk>/', UserUpdateView.as_view(), name="update_profile"),
	path('employee-profile/<int:employee_id>/<int:job_id>/', EmployeeProfileView.as_view(), name="employee_profile"),
	path('employer-jobs/', EmployerPostedJobsView.as_view(), name="employer_jobs"),
	path('employee-messages/<int:pk>/', EmployeeMessagesView.as_view(), name="employer_messages"),
	path('employee-display-messages/<int:pk>/', EmployeeDisplayMessages.as_view(), name="employee_display_messages"),
	path('add-wishlist/<int:pk>/', AddWishListView.as_view(), name="add-wishlist"),
	path('remove-from-wishlist/<int:pk>/', RemoveFromWishListView.as_view(), name="remove_from_wishlist"),
	path('mywishlist/<int:pk>/', MyWishList.as_view(), name="my_wish_list"),



]

users/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _ 
from PIL import Image 
from ckeditor.fields import RichTextField
from django.dispatch import receiver
from django.db.models.signals import post_save
from jobs.models import Job

class UserManager(BaseUserManager):
	use_in_migrations= True



	def _create_user(self,email, password, **extra_fields):
		if not email:
			raise ValueError('Your Email is not correct')

		email=self.normalize_email(email)
		user= self.model(email=email, **extra_fields)
		user.set_password(password)
		user.save(using= self._db)
		return user


	def create_user(self, email, password=None, **extra_fields):
		extra_fields.setdefault('is_superuser', False)
		return self._create_user(email, password, **extra_fields)


	def create_superuser(self, email, password, **extra_fields):
		extra_fields.setdefault('is_superuser', True)
		if extra_fields.get('is_superuser') is not True:
			raise ValueError('Superuser must have is_superuser= True')



		return self._create_user(email, password, **extra_fields) 




class Account(AbstractBaseUser, PermissionsMixin):
	email= models.EmailField(_('email address'), unique=True)
	first_name= models.CharField(_('first_name'), max_length=50, blank=False)
	last_name= models.CharField(_('last_name'), max_length=50, blank=False)
	date_joined= models.DateField(_('date_joined'), auto_now_add=True)
	is_active= models.BooleanField(_('active'), default=True)
	is_staff= models.BooleanField(_('is_staff'), default=False)
	is_employee=models.BooleanField(default=False)
	is_employer= models.BooleanField(default=False)

	objects = UserManager()

	USERNAME_FIELD='email'
	REQUIRED_FIELDS=[]

	class Meta:
		verbose_name= _('user')
		verbose_name_plural= _('users')

	def get_profile_id(self):
		return self.profile.id

	def count_unread_messages(self):
		return self.invites.filter(unread=True).count()

	def unread_messages(self):
		return self.invites.filter(unread=True).values_list('job_id', flat=True)



class Profile(models.Model):
	user = models.OneToOneField(Account, on_delete=models.CASCADE, related_name="profile")
	image = models.ImageField(upload_to="static-media/users", default="static-media/users/person_1.jpg")
	birth_day= models.DateField(default=None, blank=True, null=True)
	location= models.CharField(max_length=100, blank=True)
	resume = RichTextField(blank=True)
	company= models.CharField(max_length=250, blank=True)
	wish_list= models.ManyToManyField(Job,default=None, blank=True, related_name="wish_list")


	def __str__(self):
		return self.user.first_name+" "+self.user.last_name+""+self.user.email

	def save(self,*args, **kwargs):
		super(Profile, self).save(*args, **kwargs)

		img = Image.open(self.image)
		if img.height> 200 or img.width >200:
			new_size=(200,200)
			img.thumbnail(new_size)
			img.save(self.image.path)


@receiver(models.signals.post_save, sender=Account)
def post_save_user_signal(sender, instance, created, **kwargs):
	if created:
		instance.save()



def create_user_profile(sender, instance, created, **kwargs):
	if created:
		Profile.objects.create(user=instance)



post_save.connect(create_user_profile, sender=Account)



class Invite(models.Model):
	user= models.ForeignKey(Account, on_delete=models.CASCADE, related_name="invites")
	job= models.ForeignKey(Job, on_delete=models.CASCADE, related_name="invites")
	date= models.DateField(default=None, blank=True, null=True)
	message= RichTextField(blank=True)
	unread=models.BooleanField(default=True)

	def __str__(self):
		return self.job.title

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import Account, Profile, Invite


class AccountRegisterForm(UserCreationForm):

	CHOICES=[('is_employee', 'Employee'),
	('is_employer','Employer')]

	
	user_types= forms.CharField(label="User Type", widget=forms.RadioSelect(choices=CHOICES))

	class Meta:
		model= Account
		fields=['email', 'first_name', 'last_name']


class UserUpdateForm(forms.ModelForm):
	class Meta:
		model= Profile
		exclude =('user',)
		widgets ={
		'birth_day':forms.DateInput(attrs={'type':'date'})
		}


class InviteEmployeeForm(forms.ModelForm):
	class Meta:
		model= Invite
		fields=['date', 'message']
		widgets={
		'date':forms.DateInput(attrs={'type':'date'})
		}

users/views.py
from django.shortcuts import render, redirect
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, UpdateView
from django.contrib.auth.views import LoginView, LogoutView
from .forms import AccountRegisterForm, UserUpdateForm, InviteEmployeeForm
from .models import Profile,Account,Invite
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import DetailView, ListView
from jobs.models import Category, Job
# Create your views here.


class UserRegisterView(SuccessMessageMixin, CreateView):
	template_name= 'users/user-register.html'
	form_class=AccountRegisterForm
	success_url='/job'
	success_message="your user account has been created"


	def form_valid(self, form):
		user=form.save(commit=False)
		user_type= form.cleaned_data['user_types']

		if user_type == 'is_employee':
			user.is_employee=True

		elif user_type == 'is_employer':
			user.is_employer= True

		user.save()

		return redirect(self.success_url)	


class UserLoginView(LoginView):
	template_name='users/login.html'


class UserLogoutView(LogoutView):
	template_name='users/logout.html'

@method_decorator(login_required(login_url='/users/login'), name='dispatch')
class UserUpdateView(SuccessMessageMixin, UpdateView):
	model= Profile
	success_message="You Updated Your Profile"
	template_name="users/update.html"
	form_class=UserUpdateForm


	def form_valid(self, form):
		form.instance.user= self.request.user
		return super(UserUpdateView, self).form_valid(form)


	def get(self, request, *args, **kwargs):
		self.object=self.get_object()
		if self.object.user!= request.user:
			return HttpResponseRedirect('/job')

		return super(UserUpdateView,self).get(request, *args, **kwargs)


	def get_success_url(self):
		return reverse('users:update_profile', kwargs={'pk':self.object.pk})


class EmployeeProfileView(CreateView):
	template_name='users/employee-profile.html'
	model= Account
	form_class=InviteEmployeeForm

	def get_context_data(self, **kwargs):
		context= super(EmployeeProfileView, self).get_context_data(**kwargs)
		context['account']=Account.objects.get(pk=self.kwargs['employee_id'])
		context['profile']=Profile.objects.get(user_id=self.kwargs['employee_id'])
		context['job']=Job.objects.get(id=self.kwargs['job_id'])
		context['categories']=Category.objects.all()

		return context

	def form_valid(self, form):
		instance= form.save(commit=False)
		instance.user= Account.objects.get(pk=self.kwargs['employee_id'])
		instance.job=Job.objects.get(pk=self.kwargs['job_id'])
		instance.save()
		return super(EmployeeProfileView, self).form_valid(form)
	def get_success_url(self):
		return reverse('users:employer_jobs')

@method_decorator(login_required(login_url='/users/login'), name='dispatch')
class EmployerPostedJobsView(ListView):
	template_name='users/employer-posted-jobs.html'
	context_object_name='employer_jobs'
	model= Job
	paginate_by=3

	def get_queryset(self):
		return Job.objects.filter(employer=self.request.user).order_by('-id')



@method_decorator(login_required(login_url='/users/login'), name='dispatch')

class EmployeeMessagesView(ListView):
	model= Job
	template_name= 'users/employee-messages.html'
	paginate_by=2
	context_object_name='jobs'

	def get_queryset(self):
		return Job.objects.filter(invites__isnull=False, invites__user_id=self.request.user).order_by('-invites')


class EmployeeDisplayMessages(DetailView):
	model= Invite
	template_name='users/employee-display-messages.html'
	context_object_name='invite'


	def get_queryset(self):
		invite=self.model.objects.filter(id=self.kwargs['pk'])
		invite.update(unread=False)
		return invite

	def get(self, request, *args, **kwargs):
		self.object= self.get_object()
		if self.object.user != request.user:
			return HttpResponseRedirect('/job')
		return super(EmployeeDisplayMessages, self).get(request, *args, **kwargs)



@method_decorator(login_required(login_url='/users/login'), name='dispatch')
class AddWishListView(UpdateView):
	template_name='jobs/index.html'
	model=Profile

	def get(self, request, *args, **kwargs):
		if self.request.user.is_employee:
			job=Job.objects.get(id=self.kwargs['pk'])
			profile=Profile.objects.get(user=request.user)
			profile.wish_list.add(job)
			return redirect('jobs:home')

		else:
			return redirect('jobs:home')

@method_decorator(login_required(login_url='/users/login'), name='dispatch')
class RemoveFromWishListView(UpdateView):
	template_name='jobs/index.html'
	model=Profile

	def get(self, request, *args, **kwargs):
		if self.request.user.is_employee:
			job=Job.objects.get(id=self.kwargs['pk'])
			profile=Profile.objects.get(user=request.user)
			profile.wish_list.remove(job)
			return redirect('jobs:home')

		else:
			return redirect('jobs:home')


class MyWishList(ListView):
	template_name='users/my-wish-list.html'
	context_object_name='jobs'
	model= Job
	paginate_by= 5

	def get_queryset(self):
		return Job.objects.filter(wish_list__user_id=self.request.user.id)

	def get_context_data(self, **kwargs):
		context= super(MyWishList,self).get_context_data(**kwargs)
		if self.request.user.is_authenticated:
			context['wish_list']=Job.objects.filter(wish_list__user_id=self.request.user.id).values_list('id', flat=True)

		return context

templates/users/employee-display-messages.html
{% extends 'jobs/base.html' %}

{% load static %}

{% block content %}

    
     <div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
      <div class="overlay"></div>
      <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-start" data-scrollax-parent="true">
          <div class="col-md-8 ftco-animate text-center text-md-left mb-5" data-scrollax=" properties: { translateY: '70%' }">
          	<p class="breadcrumbs" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }"><span class="mr-3"><a href="index.html">Home <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-3"><a href="blog.html">Blog <i class="ion-ios-arrow-forward"></i></a></span> <span>Single</span></p>
            <h1 class="mb-3 bread" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Message Detail</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-degree-bg">
      <div class="container">
        <div class="row">
          <div class="col-md-8 ftco-animate">
            <h2 class="mb-3">{{ invite.date }}</h2>
            <p>{{ invite.message|safe }}</p>
            <hr>

            




          </div> <!-- .col-md-8 -->
          <div class="col-md-4 sidebar ftco-animate">
            <div class="sidebar-box">
              <form action="#" class="search-form">
                <div class="form-group">
                  <span class="icon icon-search"></span>
                  <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                </div>
              </form>
            </div>
            <div class="sidebar-box ftco-animate">
              <div class="categories">
                <h3>Categories</h3>
                {% for category in categories %}
                <li><a href="#">{{ category.title }}<span>{{ category.job_count }}</span></a></li>
               {% endfor %}
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Recent Blog</h3>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_1.jpg);"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_2.jpg);"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url(images/image_3.jpg);"></a>
                <div class="text">
                  <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> July 12, 2018</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                  </div>
                </div>
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Tag Cloud</h3>
              <div class="tagcloud">
                <a href="#" class="tag-cloud-link">dish</a>
                <a href="#" class="tag-cloud-link">menu</a>
                <a href="#" class="tag-cloud-link">food</a>
                <a href="#" class="tag-cloud-link">sweet</a>
                <a href="#" class="tag-cloud-link">tasty</a>
                <a href="#" class="tag-cloud-link">delicious</a>
                <a href="#" class="tag-cloud-link">desserts</a>
                <a href="#" class="tag-cloud-link">drinks</a>
              </div>
            </div>

            <div class="sidebar-box ftco-animate">
              <h3>Paragraph</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
            </div>
          </div>

        </div>
      </div>
    </section> <!-- .section -->

		{% endblock %}
    

templates/users/employee-messages.html
{% extends 'jobs/base.html' %}

{% load static %}

{% block content %}







<div class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_2.jpg' %}');" data-stellar-background-ratio="0.5">
  <div class="overlay"></div>
  <div class="container">
    <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start" data-scrollax-parent="true">
      <div class="col-xl-10 ftco-animate mb-5 pb-5" data-scrollax=" properties: { translateY: '70%' }">
      	<p class="mb-4 mt-5 pt-5" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">We have <span class="number" data-number="850000">0</span> great job offers you deserve!</p>
        <h1 class="mb-5" data-scrollax="properties: { translateY: '30%', opacity: 1.6 }">Your Dream <br><span>Job is Waiting</span></h1>

					<div class="ftco-search">
						<div class="row">
	            <div class="col-md-12 nav-link-wrap">
		            <div class="nav nav-pills text-center" id="v-pills-tab" role="tablist" aria-orientation="vertical">
		              <a class="nav-link active mr-md-1" id="v-pills-1-tab" data-toggle="pill" href="#v-pills-1" role="tab" aria-controls="v-pills-1" aria-selected="true">Find a Job</a>

		              <a class="nav-link" id="v-pills-2-tab" data-toggle="pill" href="#v-pills-2" role="tab" aria-controls="v-pills-2" aria-selected="false">Find a Candidate</a>

		            </div>
		          </div>
		          <div class="col-md-12 tab-wrap">
		            
		            <div class="tab-content p-4" id="v-pills-tabContent">

		              <div class="tab-pane fade show active" id="v-pills-1" role="tabpanel" aria-labelledby="v-pills-nextgen-tab">
		              	<form action="{% url 'jobs:search' %}" class="search-job" method="get">
		              		<div class="row">
		              			<div class="col-md">
		              				<div class="form-group">
			              				<div class="form-field">
			              					<div class="icon"><span class="icon-briefcase"></span></div>

                               <input type="text" class="form-control" placeholder="eg. Garphic. Web Developer" name= "job_title">
							              </div>
						              </div>
		              			</div>
		              			<div class="col-md">
		              				<div class="form-group">
		              					<div class="form-field">
			              					<div class="select-wrap">
					                      <div class="icon"><span class="ion-ios-arrow-down"></span></div>

					                      <select name="job_type" id="" class="form-control">
					                      	
					                      	<option value="full_time">Full Time</option>
					                        <option value="part_time">Part Time</option>
					                        <option value="freelance">Freelance</option>
					                        <option value="internship">Internship</option>
					                        <option value="temporary">Temporary</option>
					                      </select>
					                    </div>
							              </div>
						              </div>
		              			</div>
		              			<div class="col-md">
		              				<div class="form-group">
		              					<div class="form-field">
			              					<div class="icon"><span class="icon-map-marker"></span></div>
                        <input type="text" class="form-control" placeholder="Location" name="job_location">
							              </div>
						              </div>
		              			</div>
		              			<div class="col-md">
		              				<div class="form-group">
		              					<div class="form-field">
							                <input type="submit" value="Search" class="form-control btn btn-primary">
							              </div>
						              </div>
		              			</div>
		              		</div>
		              	</form>

                  
		              </div>





<!-- from second form -->
		              <div class="tab-pane fade" id="v-pills-2" role="tabpanel" aria-labelledby="v-pills-performance-tab">
		              	<form action="#" class="search-job">
		              		<div class="row">
		              			<div class="col-md">
		              				<div class="form-group">
			              				<div class="form-field">
			              					<div class="icon"><span class="icon-user"></span></div>
							                <input type="text" class="form-control" placeholder="eg. Adam Scott">
							              </div>
						              </div>
		              			</div>
		              			<div class="col-md">
		              				<div class="form-group">
		              					<div class="form-field">
			              					<div class="select-wrap">
					                      <div class="icon"><span class="ion-ios-arrow-down"></span></div>
					          <select name="job_type" id="" class="form-control">

					                      	<option value="">Category</option>
					                      	<option value="">Full Time</option>
					                        <option value="">Part Time</option>
					                        <option value="">Freelance</option>
					                        <option value="">Internship</option>
					                        <option value="">Temporary</option>
					                      </select>
					                    </div>
							              </div>
						              </div>
		              			</div>
		              			<div class="col-md">
		              				<div class="form-group">
		              					<div class="form-field">
			              					<div class="icon"><span class="icon-map-marker"></span></div>
							                <input type="text" class="form-control" placeholder="Location">
							              </div>
						              </div>
		              			</div>
		              			<div class="col-md">
		              				<div class="form-group">
		              					<div class="form-field">
							                <input type="submit" value="Search" class="form-control btn btn-primary">
							              </div>
						              </div>
		              			</div>
		              		</div>
		              	</form>
		              </div>
		            </div>
		          </div>
		        </div>
	        </div>
      </div>
    </div>
  </div>
</div>


	<section class="ftco-section bg-light">
		<div class="container">
			<div class="row justify-content-center mb-5 pb-3">

				{% if user.is_employee %}
      <div class="col-md-7 heading-section text-center ftco-animate">
      	<h2 class="mb-4"><span>Recent</span> Messages</h2>
      	<span class="subheading">You have {{ paginator.count }} messages</span>
        
      </div>
    	</div>
			<div class="row">


			{% for job in jobs %}

      <div class="col-md-12 ftco-animate">
					<div class="job-post-item bg-white p-4 d-block d-md-flex align-items-center">

					  <div class="mb-4 mb-md-0 mr-5">
					   <div class="job-post-item-header d-flex align-items-center">

					   	{% if job.id in user.unread_messages %}
					     <h2 class="mr-3 text-black h4" style="color:red">{{ job.title }}  </h2>

					     

					      {% else %}

					       <h2 class="mr-3 text-black h4" >{{ job.title }}  </h2>

					       {% endif %}

					     <div class="badge-wrap">
              {% if job.job_type == 'full_time' %}
					      <span class="bg-warning text-white badge py-2 px-3">Full Time</span>

              {% elif job.job_type == 'part_time' %}
              <span class="bg-info text-white badge py-2 px-3">Part Time </span>

              {% elif job.job_type == 'freelance' %}
              <span class="bg-secondary text-white badge py-2 px-3">freelance </span>

              {% elif job.job_type == 'internship' %}
              <span class="bg-info text-white badge py-2 px-3">internship </span>

              {% elif job.job_type == 'temporary' %}
              <span class="bg-danger text-white badge py-2 px-3">temporary </span>

              {% endif %}

					     </div>
					   </div>
					   <div class="job-post-item-body d-block d-md-flex">
					     <div class="mr-3"><span class="icon-layers"></span> <a href="#">{{ job.company }}</a></div>
					     <div><span class="icon-my_location"></span> <span>{{ job.location }}</span></div>
					   </div>
					  </div>

					  <div class="ml-auto d-flex">
					  	<a href="{% url 'users:employee_display_messages' pk=job.invites.all.first.id %}" class="btn btn-primary py-2 mr-1">Read Message</a>
          
          </div>

					</div>
    

      </div> <!-- end -->
      {% endfor %}

		</div>


			<div class="row mt-5">

      {% if is_paginated %}

      <div class="col text-center">
        <div class="block-27">
          <ul>
            {% if page_obj.has_previous %}

            <li><a href="?job_title={{ request.GET.job_title }}&job_type={{ request.GET.job_type}}&job_location={{ request.GET.location }}&page={{ page_obj.previous_page_number }}"><</a></li>

            {% else %}

            <li class="disabled"><span>&lt;</span></li>

            {% endif %}

            {% for i in paginator.page_range %}
            {% if page_obj.number == i %} 

            <li class="active"><span>{{ i }}</span></li>
            {% else %}
            <li><a href="?job_title={{request.GET.job_title }}&job_type={{ request.GET.job_type}}&job_location={{ request.GET.location }}&page={{ i }}">{{ i }}</a></li>
            {% endif %}

            {% endfor %}
            {% if page_obj.has_next %}

            <li><a href="?job_title={{request.GET.job_title }}&job_type={{ request.GET.job_type}}&job_location={{ request.GET.location }}&page={{ page_obj.next_page_number }} ">></a></li>
            {% else %}

            <li class="disabled">
              <span>&gt;</span></li>
            {% endif %}

          </ul>
        </div>
      </div>
      {% endif %}
    </div>

    {% else %}
    <div class="row justify-content-center mb-5 pb-3">
    <div class="col-md-7 heading-section text-center ftco-animate">
    	<h4>
    		You are not an employee
    	</h4>
    </div>
    {% endif %}
		</div>

	</section>

<section class="ftco-section ftco-counter img" id="section-counter" style="background-image: url('{% static 'images/bg_1.jpg' %}');" data-stellar-background-ratio="0.5">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-10">
	    		<div class="row">
	          <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
	            <div class="block-18 text-center">
	              <div class="text">
	                <strong class="number" data-number="1350000">0</strong>
	                <span>Jobs</span>
	              </div>
	            </div>
	          </div>
	          <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
	            <div class="block-18 text-center">
	              <div class="text">
	                <strong class="number" data-number="40000">0</strong>
	                <span>Members</span>
	              </div>
	            </div>
	          </div>
	          <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
	            <div class="block-18 text-center">
	              <div class="text">
	                <strong class="number" data-number="30000">0</strong>
	                <span>Resume</span>
	              </div>
	            </div>
	          </div>
	          <div class="col-md-3 d-flex justify-content-center counter-wrap ftco-animate">
	            <div class="block-18 text-center">
	              <div class="text">
	                <strong class="number" data-number="10500">0</strong>
	                <span>Company</span>
	              </div>
	            </div>
	          </div>
	        </div>
        </div>
    </div>
	</div>
</section>



{% endblock %}
	